### ISSUE TITLE
NoClassDefFound:ValidationConfigurationBuilder

### ISSUE THREAD

**Issue by DevNi** [java-json-tools/json-schema-validator#109]
@fge 
I am using json-schema-validator 2.2.5 version for which I used the following dependency:

<dependency>  
<groupId>com.github.fge</groupId>  
<artifactId>json-schema-validator</artifactId>  
<version>2.2.5</version> 
</dependency>

But when I run a simple code I am getting the following error,

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.fge.jsonschema.cfg.ValidationConfigurationBuilder at com.github.fge.jsonschema.cfg.ValidationConfiguration.newBuilder(ValidationConfiguration.java:92) at com.github.fge.jsonschema.cfg.ValidationConfiguration.byDefault(ValidationConfiguration.java:102) at com.github.fge.jsonschema.main.JsonSchemaFactoryBuilder.(JsonSchemaFactoryBuilder.java:68) at com.github.fge.jsonschema.main.JsonSchemaFactory.newBuilder(JsonSchemaFactory.java:123) at com.github.fge.jsonschema.main.JsonSchemaFactory.byDefault(JsonSchemaFactory.java:113)

Please help me with this 

Thanks,
DevNi

**Comment by annadobrowolska** [comment]
I had similar problem on Weblogic 12.1.3.0.0 with 2.2.5 json-schema-validator version. After add

```
<prefer-application-packages>
            <package-name>javax.ws.rs.*</package-name>
            <package-name>org.joda.time.*</package-name>
            <package-name>org.apache.commons.lang.*</package-name>
            <package-name>com.sun.jersey.*</package-name>
            <package-name>org.glassfish.jersey.*</package-name>
</prefer-application-packages>
```
to my weblogic.xml problem disappeared.
