### ISSUE TITLE
Bug in -core: URI normalization fails with URNs/"opaque" URIs (was Validation breaks when using Jackson >= 2.4.2)

### ISSUE THREAD

**Issue by tkruse** [java-json-tools/json-schema-validator#119]
For us, tests break with weird Exception at bottom.

```

private static final JsonValidator VALIDATOR = JsonSchemaFactory.byDefault().getValidator();

 @Test
    public void verifySuccessfulValidation() throws ProcessingException, IOException {

        final String validStatusUpdate = "{\"@type\": \"APPLICATION_STATUS_UPDATED\", \"applicationId\": \"id\", \"projectTitle\": \"title\", \"userId\": \"id\", \"timestamp\": [2014, 5, 28, 8, 47, 30, 500]}";
        final ProcessingReport validReport = VALIDATOR.validate(incomingSchema, JsonLoader.fromString(validStatusUpdate));
    }
```

I notice that the schema we generate using Jackson 2.4.3 now has additional lines:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "accountRestrictionsUpdated": {
+            "id": "urn:jsonschema:com:example:AccountRestrictionsUpdated",
         ...
```

The new line with `urn:` seems a likely cause.
Not sure how to best reproduce this.

Exception:

```
MessageSchemaGeneratorTest > verifySuccessfulValidation FAILED
    com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: How did I get there??
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at com.github.fge.jsonschema.core.processing.CachingProcessor.process(CachingProcessor.java:109)
        at com.github.fge.jsonschema.processors.validation.InstanceValidator.process(InstanceValidator.java:136)
        at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:56)
        at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:34)
        at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
        at com.github.fge.jsonschema.main.JsonValidator.validate(JsonValidator.java:104)
        at com.github.fge.jsonschema.main.JsonValidator.validate(JsonValidator.java:124)
        at MessageSchemaGeneratorTest.verifySuccessfulValidation(MessageSchemaGeneratorTest.java:66)

        Caused by:
        com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: How did I get there??
            at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
            at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
            at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
            at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
            at com.github.fge.jsonschema.core.processing.CachingProcessor.process(CachingProcessor.java:109)
            at com.github.fge.jsonschema.processors.validation.ValidationChain.process(ValidationChain.java:107)
            at com.github.fge.jsonschema.processors.validation.ValidationChain.process(ValidationChain.java:57)
            at com.github.fge.jsonschema.core.processing.ProcessorMap$Mapper.process(ProcessorMap.java:166)
            at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
            at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:128)
            at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:120)
            at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
            at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
            at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
            at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
            ... 11 more

            Caused by:
            java.lang.IllegalStateException: How did I get there??
                at com.github.fge.jsonschema.core.util.URIUtils$2.apply(URIUtils.java:113)
                at com.github.fge.jsonschema.core.util.URIUtils$2.apply(URIUtils.java:87)
                at com.github.fge.jsonschema.core.util.URIUtils.normalizeURI(URIUtils.java:238)
                at com.github.fge.jsonschema.core.ref.JsonRef.fromURI(JsonRef.java:183)
                at com.github.fge.jsonschema.core.ref.JsonRef.fromString(JsonRef.java:207)
                at com.github.fge.jsonschema.core.tree.BaseSchemaTree.idFromNode(BaseSchemaTree.java:278)
                at com.github.fge.jsonschema.core.tree.BaseSchemaTree.nextRef(BaseSchemaTree.java:303)
                at com.github.fge.jsonschema.core.tree.BaseSchemaTree.<init>(BaseSchemaTree.java:145)
                at com.github.fge.jsonschema.core.tree.CanonicalSchemaTree.<init>(CanonicalSchemaTree.java:79)
                at com.github.fge.jsonschema.core.tree.CanonicalSchemaTree.append(CanonicalSchemaTree.java:86)
                at com.github.fge.jsonschema.core.keyword.syntax.SyntaxProcessor.validate(SyntaxProcessor.java:118)
                at com.github.fge.jsonschema.core.keyword.syntax.SyntaxProcessor.rawProcess(SyntaxProcessor.java:70)
                at com.github.fge.jsonschema.core.keyword.syntax.SyntaxProcessor.rawProcess(SyntaxProcessor.java:45)
                at com.github.fge.jsonschema.core.processing.RawProcessor.process(RawProcessor.java:77)
                at com.github.fge.jsonschema.core.processing.RawProcessor.process(RawProcessor.java:41)
                at com.github.fge.jsonschema.core.processing.ProcessorChain$ProcessorMerger.process(ProcessorChain.java:190)
                at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
                at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:128)
                at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:120)
                at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
                at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
                at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
                at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
                ... 25 more

                Caused by:
                java.net.URISyntaxException: Expected scheme-specific part at index 4: urn:
                    at java.net.URI$Parser.fail(URI.java:2829)
                    at java.net.URI$Parser.failExpecting(URI.java:2835)
                    at java.net.URI$Parser.parse(URI.java:3038)
                    at java.net.URI.<init>(URI.java:680)
                    at com.github.fge.jsonschema.core.util.URIUtils$2.apply(URIUtils.java:110)
                    ... 47 more
```

**Comment by njaiswal** [comment]
Is this fixed for draft 3 schema file as well?
I am using 2.2.6 dependency for json-schema-validator and schema is draft 3 and get identical error message:

--- BEGIN MESSAGES ---
fatal: URI scheme "urn" not supported (URI: "urn:jsonschema:com:x:y:z#")
    level: "fatal"
    scheme: "urn"
    uri: "urn:jsonschema:com:x:y:Z:ClassName#"
    info: "other messages follow (if any)"
---  END MESSAGES  ---

**Comment by fge** [comment]
@njaiswal that's not the same problem at all you have here, look at what the error message says carefully...
