### ISSUE TITLE
No class Def found @ ValidationConfigurationBuilder

### ISSUE THREAD

**Issue by rajesh2win** [java-json-tools/json-schema-validator#121]
18 Oct, 2014 6:20:56 AM IST> <Warning> <EJB> <BEA-010065> <MessageDrivenBean threw an Exception in onMessage(). The exception was:
java.lang.NoClassDefFoundError: com/github/fge/jsonschema/cfg/ValidationConfigurationBuilder.
ava.lang.NoClassDefFoundError: com/github/fge/jsonschema/cfg/ValidationConfigurationBuilder
       at com.github.fge.jsonschema.cfg.ValidationConfiguration.newBuilder(ValidationConfiguration.java:92)
       at com.github.fge.jsonschema.cfg.ValidationConfiguration.byDefault(ValidationConfiguration.java:102)
       at com.github.fge.jsonschema.main.JsonSchemaFactoryBuilder.<init>(JsonSchemaFactoryBuilder.java:68)
       at com.github.fge.jsonschema.main.JsonSchemaFactory.newBuilder(JsonSchemaFactory.java:123)
       at com.github.fge.jsonschema.main.JsonSchemaFactory.byDefault(JsonSchemaFactory.java:113)

**Comment by Kverma517** [comment]
I am getting the same.
