### ISSUE TITLE
Exception in Android: Failed resolution of: Ljavax/script/ScriptEngineManager

### ISSUE THREAD

**Issue by kayvannj** [java-json-tools/json-schema-validator#273]
I'm trying to integrate this lib to my android project and I have passed all the initial integration challenges (with packagingOptions and such) and I see the lib compile and parse the schema (outputting `Applying schema: ...`) but right after it crashes with this exception:

```
2018-08-23 10:22:34.317 28269-28269/com.x E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.doximity.doximitydroid.x, PID: 28269
    com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/script/ScriptEngineManager;
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3850)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3874)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4799)
        at com.github.fge.jsonschema.core.processing.CachingProcessor.process(CachingProcessor.java:122)
        at com.github.fge.jsonschema.processors.validation.InstanceValidator.process(InstanceValidator.java:109)
        at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:56)
        at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:34)
        at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
        at com.github.fge.jsonschema.main.JsonSchemaImpl.doValidate(JsonSchemaImpl.java:77)
        at com.github.fge.jsonschema.main.JsonSchemaImpl.validate(JsonSchemaImpl.java:100)
        at com.github.fge.jsonschema.main.JsonSchemaImpl.validate(JsonSchemaImpl.java:110)
...
```

These kind of exceptions happen when an expected java class doesn't exists in Android's SDK but based on the descriptions of the lib, it should be compatible with Android! Am I doing something wrong? any help is appreciated.

**Comment by xavier-rigau** [comment]
Me too

**Comment by JiashuGuo** [comment]
I just got exact same error as yours when use json-schema-validator in Android, have you get an answer?

**Comment by JiashuGuo** [comment]
Just solve it... try if add compile 'io.apisense:rhino-android:1.0' in gradle works. Also, refer to below url:
https://stackoverflow.com/questions/14511468/java-android-validate-string-json-against-string-schema
for a complete solution of use json-schema-validator in Android.
