### ISSUE TITLE
getJsonSchema with `ptr` path to a missing node causes NPE 

### ISSUE THREAD

**Issue by Capstan** [java-json-tools/json-schema-validator#291]
In v2.2.10, if you use the two-argument `getJsonSchema` and a syntactically valid `ptr` but to a path that doesn't exist in the `schema`, you'll get the following:

```
java.lang.NullPointerException
	at com.github.fge.jsonschema.main.JsonValidator.buildJsonSchema(JsonValidator.java:188)
	at com.github.fge.jsonschema.main.JsonSchemaFactory.getJsonSchema(JsonSchemaFactory.java:205)
```
The call to `SchemaTree.setPointer` in `JsonValidator.java:187` ends up replacing the tree with `null`, which then NPEs on the next line. I don't know what the contract `SchemaTree.setPointer` has for pointers outside the bounds of said `SchemaTree`, but this might be better if the `load` and the `setPointer` statements were separated so that if the latter returns `null`, an appropriate `ProcessingException` can be thrown.

**Comment by Capstan** [comment]
Perhaps this is the `SchemaTree`'s fault… it looks like `buildJsonSchema` already tries to do the right thing if the tree's node is the missing node.

**Comment by Capstan** [comment]
Turns out that the NPE is not from `setPointer`, but from the post-`setPointer` `SchemaTree`'s `getNode`. The following snippet added to json-schema-core's SchemaTreeTest repros the problem:

```
    @Test
    public void danglingRefToSubschema() throws JsonPointerException
    {
        final ObjectNode node = FACTORY.objectNode();
        final SchemaTree tree
             = new CanonicalSchemaTree(SchemaKey.anonymousKey(), node);
        assertNotEquals(tree, null);
        final SchemaTree subtree = tree.setPointer(new JsonPointer("/missing"));
        assertNotEquals(subtree, null);
        assertNotEquals(subtree.getNode(), null);
        assertEquals(subtree.getNode().isMissingNode(), true);
    }
```

**Comment by Capstan** [comment]
This looks like a disparity between constructors of `BaseSchemaTree`. Two use `JsonPointer.path` which will return the missing node, but the third uses `JsonPointer.get`, which will just return null.

**Comment by Capstan** [comment]
Fixed in https://github.com/java-json-tools/json-schema-core/pull/56
