### ISSUE TITLE
ClassLoader Issues with ObjectNode

### ISSUE THREAD

**Issue by matthewjmason** [java-json-tools/json-schema-validator#30]
I see that you have overriden com.fasterxml.jackson.databind.node.ObjectNode in your jar. This is causing class loading issues for when trying to invoke your code. When I have both json-schema-validator and jackson-databind on my classpath in eclipse, it is loading the jackson-databind's version of ObjectNode instead of yours. This is causing the following error:

`java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ObjectNode.asMap()Ljava/util/Map;
    at org.eel.kitchen.jsonschema.validator.ObjectValidator.<init>(ObjectValidator.java:68)
    at org.eel.kitchen.jsonschema.validator.InstanceValidator.validate(InstanceValidator.java:89)
    at org.eel.kitchen.jsonschema.main.JsonSchema.validate(JsonSchema.java:71)
    at com.dibs.json_validator.AppTest.testJSON(AppTest.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at junit.framework.TestCase.runTest(TestCase.java:154)
    at junit.framework.TestCase.runBare(TestCase.java:127)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:118)
    at junit.framework.TestSuite.runTest(TestSuite.java:208)
    at junit.framework.TestSuite.run(TestSuite.java:203)
    at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)`

Is there some standard workaround or solution for this? I would prefer not to mess with my classloader. I am using the latest version of the 1.4 branch.

**Comment by anupam2502** [comment]
In my code I am using ProcessingReport report = schema.validate(jsonNode); There is no compilation issue and when I run the test from the same project it is not giving any exception. But when I execute the same by adding dependency of my current project to another project and then running the test from that project, I am getting the following error : java.lang.NoSuchMethodError: com.github.fge.jsonschema.main.JsonSchema.validate(Lcom/fasterxml/jackson/databind/JsonNode;)Lcom/github/fge/jsonschema/core/report/ProcessingReport;
