### ISSUE TITLE
Crash while invoked from Intellij Idea as a part of JUnit test

### ISSUE THREAD

**Issue by tibidoh** [java-json-tools/json-schema-validator#39]
I've adopted the validator for testing of my REST interface responses. When I run my tests from maven everything is ok, but if I run tests from Intellij Idea validator crashes. The Idea runs  both static initialisation of RhinoHelper and invocation of regexIsValid() method  from the same thread and validator crashes while  entering Context from regexIsValid() method  because Context is the one created during static init and it is sealed. Here's the stacktrace I have: 

<pre>
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2256)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3980)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3984)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4868)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4874)
    at com.github.fge.jsonschema.validator.JsonValidatorCache.getValidator(JsonValidatorCache.java:97)
    at com.github.fge.jsonschema.main.JsonSchema.validate(JsonSchema.java:69)
~~
    My code
~~
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:76)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.lang.IllegalStateException
    at org.mozilla.javascript.Context.onSealedMutation(Context.java:712)
    at org.mozilla.javascript.Context.enter(Context.java:417)
    at org.mozilla.javascript.Context.enter(Context.java:398)
    at org.mozilla.javascript.Context.enter(Context.java:378)
    at com.github.fge.jsonschema.util.RhinoHelper.regexIsValid(RhinoHelper.java:107)
    at com.github.fge.jsonschema.syntax.common.PatternSyntaxChecker.checkValue(PatternSyntaxChecker.java:55)
    at com.github.fge.jsonschema.syntax.AbstractSyntaxChecker.checkSyntax(AbstractSyntaxChecker.java:63)
    at com.github.fge.jsonschema.syntax.SyntaxValidator.validate(SyntaxValidator.java:75)
    at com.github.fge.jsonschema.syntax.draftv3.DraftV3PropertiesSyntaxChecker.checkValue(DraftV3PropertiesSyntaxChecker.java:93)
    at com.github.fge.jsonschema.syntax.AbstractSyntaxChecker.checkSyntax(AbstractSyntaxChecker.java:63)
    at com.github.fge.jsonschema.syntax.SyntaxValidator.validate(SyntaxValidator.java:75)
    at com.github.fge.jsonschema.validator.JsonValidatorCache$2.load(JsonValidatorCache.java:132)
    at com.github.fge.jsonschema.validator.JsonValidatorCache$2.load(JsonValidatorCache.java:115)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3579)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2372)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2335)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2250)
    ... 34 more
</pre>

For now I have a hack:

``` java
Runnable staticInitHack = new Runnable() {
    @Override public void run() {
        try {
            RhinoHelper.regexIsValid( "^ $" );
        } catch ( Exception ignored ) { }
    }
};
Thread thread = new Thread( staticInitHack );
thread.start();
try {
    thread.join();
} catch ( InterruptedException e ) {
    Assert.fail();
}
```

It simply does static initialisation of RhinoHelper from another thread and after that everything goes fine.

**Comment by devorbh** [comment]
Hi, I'm getting below error when trying to validate my schema and json

com.github.fge.jsonschema.exceptions.InvalidSchemaException: invalid schema, cannot continue
at com.github.fge.jsonschema.processors.validation.ValidationChain$1.doException(ValidationChain.java:68)
at com.github.fge.jsonschema.report.ProcessingMessage.asException(ProcessingMessage.java:292)
at com.github.fge.jsonschema.processing.ProcessorChain$1.process(ProcessorChain.java:133)
at com.github.fge.jsonschema.processing.ProcessorChain$ProcessorMerger.process(ProcessorChain.java:187)
at com.github.fge.jsonschema.processing.ProcessingResult.of(ProcessingResult.java:79)
at com.github.fge.jsonschema.processing.CachingProcessor$1.load(CachingProcessor.java:110)
at com.github.fge.jsonschema.processing.CachingProcessor$1.load(CachingProcessor.java:102)
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)

My schema is using enum and patterns, how to deal with it.

**Comment by huggsboson** [comment]
@devorbh it looks like your schema was invalidly specified.  Any chance you can paste that here?
